import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";

const vazirmatn = Vazirmatn({
  variable: "--font-Vazirmatn",
  subsets: ["arabic"],
});

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`grid gap-6 bg-gradient-to-l bg-bg-black ${inter.variable}  ${vazirmatn.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
